### ISSUE TITLE
Class "Flowmailer\API\Flowmailer" not found on Ubuntu server but it does work locally

### ISSUE THREAD

**Issue by VerburgtJimmy** [flowmailer/flowmailer-php-sdk#1]
I just import it using this: 
`use Flowmailer\API\Flowmailer;`.

I don't really know what more information I should post so if someone knows what to do? Most people are suggesting a capital namespace error somewhere but I can't find it.

Already did dump-autoload

**Comment by reyostallenberg** [comment]
I'm sorry for the late response.
I think you have managed get it working by now.
If not, please respond again and I can try to help you
